### PR TITLE
Adding the initial DCD

### LINKED ISSUE #129: Create DCD

### PR DESCRIPTION
**Pull request by Madictian**
Adding the visio document and PDF for the initial draft of the DCD for our main scenario.

Closes #129

### CODE REVIEW

**Review by Bombohog — CHANGES_REQUESTED** [review]
The last three setters methods in the controller class and customer class need a bit C for customer and the last setter also need "customerAddress" instead of "Address"

**Review by Bombohog — APPROVED** [review]
I can accept it.

**Review by MBRzealand — APPROVED** [review]
Looks good homie

**Review by MBRzealand — CHANGES_REQUESTED** [review]
Please move diagram up a bit to remove the excess space, and fix the one fucked arrow

**Review by Bombohog — CHANGES_REQUESTED** [review]
Please delete the pdf and vsdx from outside the folders.

**Review by Bombohog — APPROVED** [review]
I approve.

**Pull request merged**
