### PR TITLE
Added new version of DOM

### LINKED ISSUE #156: UpdateDOMtoincludeCutomizationExtend

### PR DESCRIPTION
**Pull request by Hjordrup**
Closes #156

### CODE REVIEW

**Review by Bombohog — CHANGES_REQUESTED** [review]
Change "s" with "S" in the top-left "specifies".

**Review by Bombohog — APPROVED** [review]
Looks good.

**Review by MBRzealand — COMMENTED** [review]
Would it not make sense to already include price variables in wall class?
since customization is iterated in now, we need prices for each additional item picked with checkboxes/spinners, they currently have no price, hence customization is semi-pointless?

**Review by Bombohog — APPROVED** [review]
I approve.

**Pull request merged**
